### PR TITLE
Fix trophic level

### PR DESCRIPTION
**Pull request by tpoisot**
See #202 and #204 

This PR notably

- uses `trophic_level` for the basic value, and `fractional_trophic_level` for the version weighted by degree (this was switched before)
- allows flexibility in deciding how the information on chain length is summarized (through the `f` keyword to both functions)
- uses `dijkstra` for the shortest paths in `trophic_level`

### CODE REVIEW

**Comment by tpoisot** [comment]
@mjsmith037 do you want me to add you to the repo? This would make it easier to work on this series of fixes.

**Comment by mjsmith037** [comment]
While I have a certain *enthusiasm* for this package, I am not sure it is matched by technical skill :smile:. Nevertheless, I'm happy to be added to the repo and contribute what I can!

**Comment by tpoisot** [comment]
I have expanded `trophic_level` so the user can pick the min, max, or average chain length. That being said, this is calculated on the *shortest* path, and I'm not sure if this should be the case, of if we need to enumerate *all* paths (which is a little more time consuming, but not by much).

**Comment by tpoisot** [comment]
OK, the pseudo-inverse is only used if the diet matrix is non-invertible, so that's cool.

The omnivory code is now in the same file as trophic level, and there's a manual page.

**Pull request merged**
